.github/workflows/release.yml
Add a github action workflow to build docker images and publish to dockerHub on release created.
the following docker images will be created:
- cloudnexusopsdockerhub/kraken-app-controller:{tag}
- cloudnexusopsdockerhub/kraken-app-hub:{tag}
- cloudnexusopsdockerhub/kraken-app-agent:{tag}
- cloudnexusopsdockerhub/kraken-app-portal:{tag}
To support publish docker images, the two secrets have been added into the repo setting:
- DOCKER_USERNAME
- DOCKER_PASSWORD
=> build(misc): add github action to build/publish docker images

kraken-app/kraken-app-agent/pom.xml, kraken-app/kraken-app-controller/pom.xml, kraken-app/kraken-app-hub/pom.xml, kraken-app/kraken-app-portal/package-lock.json, kraken-app/kraken-app-portal/package.json, kraken-app/pom.xml, kraken-java-sdk/kraken-java-sdk-auth/pom.xml, kraken-java-sdk/kraken-java-sdk-controller/pom.xml, kraken-java-sdk/kraken-java-sdk-core/pom.xml, kraken-java-sdk/kraken-java-sdk-data/pom.xml, kraken-java-sdk/kraken-java-sdk-gateway/pom.xml, kraken-java-sdk/kraken-java-sdk-mef/pom.xml, kraken-java-sdk/kraken-java-sdk-sync/pom.xml, kraken-java-sdk/kraken-java-sdk-test/pom.xml, kraken-java-sdk/pom.xml, pom.xml
=> build(misc): bump version to 1.0.1 

.github/workflows/lint-pull-request.yaml
=> build(ci-cd): rename lint-pr-title to lint-pull-request

README.md, docker/docker-compose.yaml, kraken-app/kraken-app-agent/src/main/resources/application.yaml, kraken-app/kraken-app-controller/src/main/resources/application.yaml, kraken-app/kraken-app-hub/src/main/resources/application.yaml
1. Add more steps into README on how to run kraken
2. Support the following env variables to customize DB connection
- DB_URL
- DB_USERNAME
- DB_PASSWORD
=> docs(misc): add more details on how to run kraken

.github/workflows/release.yml, README.md, docker/docker-compose.yaml, docker/dockerBuild.sh
on github release created:
- build docker images and add `latest` tag
pull the latest docker images in docker-compose.yaml
=> build(misc): tag latest to docker images for each release

.github/CODEOWNERS
Add https://github.com/orgs/mycloudnexus/teams/kraken-code-approver as the code owners, and modify the PR protection rule
=> build(misc): add github codeowners

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/model/MgmtProperty.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/model/SystemInfo.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/SystemInfoService.java
add field productName in response 
https://github.com/mycloudnexus/kraken/issues/60
=> feat(sdk):  Display product information and Kraken information

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.add.yaml
fix the title for create eline order template
issue: https://github.com/mycloudnexus/kraken/issues/37
=> fix(sdk): fix the title issue for create eline order template

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/TemplateUpgradeService.java
fix throw exception check if it is the latest template. 
The fuction should return true/false.rather than throwing exception
https://github.com/mycloudnexus/kraken/issues/30
=> fix(sdk): fix throw exception check if it is the latest template

kraken-app/kraken-app-hub/src/test/resources/mock/apis/api.quote.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.quote.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.5.8.yaml
https://github.com/mycloudnexus/kraken/issues/26
=> fix(sdk): added javascript error message for quote

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/ComponentMgmtController.java
allow to save mappper when upgrading
https://github.com/mycloudnexus/kraken/issues/28
=> fix(sdk): allow to save mappper when upgrading

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.5.15.yaml
https://github.com/mycloudnexus/kraken/issues/55
=> fix(sdk): fix itemTerm in target file

kraken-app/kraken-app-portal/src/hooks/user/useUser.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentOverview/index.module.scss, kraken-app/kraken-app-portal/src/pages/EnvironmentOverview/index.tsx
fix deployed by doesn't include info for internal users
- [[Improvement] Show Internal user name in deploy history list of mapping page and deployment history of deployments](https://github.com/mycloudnexus/kraken/issues/157)
- [Deployment page UX improvement](https://github.com/mycloudnexus/kraken/issues/156)
=> fix(portal): fix deployed by doesn't include info for internal users

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/TemplateUpgradeService.java
https://github.com/mycloudnexus/kraken/issues/163
=> fix(sdk):  check  whether mapper exites when query control plane deployment details

kraken-app/kraken-app-agent/src/main/resources/application.yaml, kraken-app/kraken-app-controller/pom.xml
- remove default scheduled job in agent and should each independently configured
-  import kraken-java-sdk-data to control plane
- https://github.com/mycloudnexus/kraken/issues/174
=> fix(sdk): import pom of kraken-java-sdk-data to control plane

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/v2/AuditCollectorV2Controller.java
https://github.com/mycloudnexus/kraken/issues/186
=> fix(sdk): remove status condition

kraken-app/kraken-app-portal/src/pages/APIServerList/components/APIServerCard.tsx
When moues over on the "In use" tag, only the tag changes to "Check details" link button, the server itself should no change/move.
=> fix(portal): adjust hover style bug

kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/PushKrakenVersionService.java, kraken-java-sdk/kraken-java-sdk-sync/src/test/java/com/consoleconnect/kraken/operator/sync/service/PushKrakenVersionServiceTest.java
update event state instead of generate a new event to avoid too many event records in external system
https://github.com/mycloudnexus/kraken/issues/87
=> fix(sdk): improvement on sync kraken version

kraken-app/kraken-app-portal/src/pages/NewAPIServer/components/SelectAPIServer.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIServer/index.tsx
Remove form object as props to avoid empty values
#184
=> fix(portal): fix form undefined from validation

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.eline.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.eline.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.uni.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.uni.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.5.18.yaml
fix completionDate issue
https://github.com/mycloudnexus/kraken/issues/212
=> fix(sdk): fix completionDate issue

kraken-app/kraken-app-portal/src/components/Header/index.tsx, kraken-app/kraken-app-portal/src/pages/APIServerList/components/APIServerCard.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/index.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/HeaderMapping/index.module.scss, kraken-app/kraken-app-portal/src/pages/NewAPIMapping/index.tsx, kraken-app/kraken-app-portal/src/stores/tutorial.store.tsx
fix api mapping tutorial component
- [[1.0][rc][BUG] [FE] api guide component error](https://github.com/mycloudnexus/kraken/issues/180)
=> fix(portal): fix api mapping tutorial component

kraken-app/kraken-app-portal/src/hooks/product/index.ts, kraken-app/kraken-app-portal/src/pages/Buyer/index.tsx, kraken-app/kraken-app-portal/src/stores/buyer.store.tsx
fix buyer management pagination doesn't work properly
- [[1.0][rc] no pagination support in buyer management](https://github.com/mycloudnexus/kraken/issues/223)
Buyer management: not showing pagination and pagination is not working properly.
=> fix(portal): fix buyer management pagination doesn't work properly

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.order.eline.delete.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.order.uni.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.uni.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.5.24.yaml
Added orderDate for deleting order
https://github.com/mycloudnexus/kraken/issues/228
=> fix(sdk): added order date for order deletion

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/BuyerService.java
Made some improvements to the error tips for creating the buyer.
https://github.com/mycloudnexus/kraken/issues/187
=> fix(sdk): improve buyer error tips

kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/push/PushAPIActivityLogScheduler.java
Use /callback/agent/events path in scheduler
https://jira.pccwglobal.com/browse/KRAKEN-792
=> feat(sdk): kraken-792 - use /callback/agent/events path in scheduler

kraken-app/kraken-app-portal/src/__test__/pages/Homepage/components/ActivityDiagrams.test.tsx, kraken-app/kraken-app-portal/src/__test__/pages/MappingTemplate/components.test.tsx, kraken-app/kraken-app-portal/src/__test__/pages/StandardAPIMapping/index.test.tsx, kraken-app/kraken-app-portal/src/components/SideNavigation/index.tsx, kraken-app/kraken-app-portal/src/pages/HomePage/components/ActivityDiagrams/ApiActivityDiagram/index.tsx, kraken-app/kraken-app-portal/src/pages/HomePage/components/ActivityDiagrams/MostPopularEndpoints/index.tsx, kraken-app/kraken-app-portal/src/pages/HomePage/components/ActivityDiagrams/NoData/index.tsx, kraken-app/kraken-app-portal/src/pages/HomePage/components/ActivityDiagrams/index.module.scss, kraken-app/kraken-app-portal/src/pages/HomePage/components/ActivityDiagrams/index.tsx, kraken-app/kraken-app-portal/src/pages/HomePage/components/QuickStartGuide/index.tsx, kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionSelect/index.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/HeaderMapping/index.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIMapping/index.tsx, kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/components/MappingDetailsList/index.tsx, kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.module.scss, kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.tsx
- support dragging right border of standard api mapping left panel to resize
- fix some typo issues and minor logic
- [[BUG] Font size and font weight not correct](https://github.com/mycloudnexus/kraken/issues/177)
- [[BUG] [FE] Mapping setting page - Seller API Path should be left-aligned](https://github.com/mycloudnexus/kraken/issues/252)
- [[BUG] Release history page issue](https://github.com/mycloudnexus/kraken/issues/203)
- [[BUG] Empty states of API activity charts](https://github.com/mycloudnexus/kraken/issues/196)
- [[BUG] Text color not correct](https://github.com/mycloudnexus/kraken/issues/193)
- [[FEATURE] Make API mapping page left panel draggable](https://github.com/mycloudnexus/kraken/issues/246)
=> fix(portal): fix regression bugs

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/StartGuideController.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/start/StartGuideService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/api/StartGuideControllerTest.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/service/start/StartGuideServiceTest.java
Remove kind RequestParam from /start/guide endpoint and use COMPONENT_API_TARGET_SPEC in service.
https://github.com/mycloudnexus/kraken/issues/247
=> feat(sdk): kraken-247 - remove kind from /start/guide endpoint and use COMPONENT_API_TARGET_SPEC in service

kraken-app/kraken-app-portal/src/hooks/pushApiEvent/index.ts, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/index.tsx, kraken-app/kraken-app-portal/src/services/pushApiActivity.ts
Allows to fetch enabled/disabled flag of push log button from API
=> feat(portal): add push button enabled flag from API

kraken-app/kraken-app-portal/src/components/form/AutoGrowingInput.tsx, kraken-app/kraken-app-portal/src/pages/HomePage/components/ActivityDiagrams/ErrorDiagram/index.tsx, kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionSelect/DetailDrawer.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIMapping/index.tsx, kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/components/MappingDetailsList/index.module.scss, kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.module.scss
- remove compare button in api mapping
- make left panel scrollable
- [[FEATURE] Make API mapping page left panel draggable](https://github.com/mycloudnexus/kraken/issues/246)
- [[FE][Improvement] remove unused button and add necessary tooltip](https://github.com/mycloudnexus/kraken/issues/274)
=> fix(portal): remove compare button in api mapping & make left panel scrollable

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/push/ApiActivityPushService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/service/push/ApiActivityPushServiceTest.java
Reject the push request if 0 records to push
https://github.com/mycloudnexus/kraken/issues/273
=> feat(sdk): kraken-247 - reject the push request if 0 records to push

kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/index.tsx
- Hacks Range picker from Antd to respect selected values from other component
https://github.com/mycloudnexus/kraken/issues/219
=> fix(portal): adjust range picker props to show dates from external props

kraken-app/kraken-app-hub/src/test/resources/mock/mapping-matrix/mapping.matrix.address.validation.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.address.validation.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.6.5.yaml
Deleting the unnecessary checking rules for the street name in the address validation matrix file.
https://github.com/mycloudnexus/kraken/issues/276
=> fix(sdk): deleting checking rules for the streetName

kraken-java-sdk/kraken-java-sdk-test/pom.xml
Upgrading spring-webflux to 6.1.14 in pom.xml of kraken-java-sdk-test for security issues
https://github.com/mycloudnexus/kraken/issues/309
=> fix(sdk): upgrade spring-webflux version to 6.1.14

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java
Added validation for empty string such as "".
https://github.com/mycloudnexus/kraken/issues/313
Integration test in localhost:
=> fix(sdk): added checking for empty string

kraken-app/kraken-app-portal/src/components/APIServerModal/APIViewer.tsx, kraken-app/kraken-app-portal/src/components/APIViewerContent/index.tsx, kraken-app/kraken-app-portal/src/components/SpecDrawer/index.tsx, kraken-app/kraken-app-portal/src/pages/APIServerList/components/APIServerCard.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIServer/index.tsx, kraken-app/kraken-app-portal/src/utils/helpers/base64.ts
patch from https://github.com/mycloudnexus/kraken/pull/324/files
seller api save failed
- #321
=> fix(portal): seller api save failed

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/LifeStatusEnum.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogServiceAtControlPlaneTest.java
1. kraken can allow user to configure a log retention period like 3 months, 6 months etc
retention period of control plane, stage data plane and prod data plane can be configured differently
retention period for basic data and detail data of api activity can be configured separately
2. kraken can auto delete api activity detail logs physically out of retention period
user can set to delete detail data for specific method, e.g. only to delete GET data and keep data for other methods
3. the feature can be disabled and enabled
4. the auto delete shouldn't impact api activity statistics calculation
https://github.com/mycloudnexus/kraken/issues/295
=> feat(sdk): auto delete api activity logs out of retention period

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.add.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/SellerContactControllerTest.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/facet/ComponentAPITargetFacets.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.1.yaml
added a property named 'allowValueLimit' to mark whether allowing customized value limitation
https://github.com/mycloudnexus/kraken/issues/344
Only changing configurations, no need to test.
=> feat(sdk): added flag of allowing value limitation

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/EndpointAuditController.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/audit/EndpointAuditService.java
The total records number is not correct in the list of audit logs.
The above issue has been fixed in this PR.
https://github.com/mycloudnexus/kraken/issues/335
Unit test
=> fix(sdk): fixed total numbers in audit log list

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.address.validate.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.delete.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.add.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.delete.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/MappingTypeEnum.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/facet/ComponentAPITargetFacets.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/Constants.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/MappingTypeEnumTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunnerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/deployment-config/components/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/deployment-config/components/api-targets-mappers/api-target-mapper.order.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.address.validate.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.2.yaml
Separating the discrete indicator of the source value from the source type and make it more clear in the front side.
https://github.com/mycloudnexus/kraken/issues/358
1.The value of the source type is mixed with the flag of discrete or continuous for the source values. 
It's not clear to interact with the front side.
2.Another problem is the kind of 'constantNumber' which should not be defined as a data type kind. In fact, the constant can be used for many other data types. 
The constantNumber' kind has been removed finally.
This PR has made some improvement on the issue above.
Integration testing in localhost and show cases with QA.
=> feat(sdk): separated the source type and discrete flag of source value

kraken-app/kraken-app-hub/src/test/resources/expected/expected-2-address.retrieve.json, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.address.retrieve.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.address.retrieve.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.address.retrieve.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.address.retrieve.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.2.yaml
Removed the 'associatedGeographicAddress' for address retrieving based on the feedback.
https://github.com/mycloudnexus/kraken/issues/365
Integration test in localhost.
=> fix(sdk): removed the associated geographic address for address retrieving

kraken-app/kraken-app-hub/src/test/resources/mock/mapping-matrix/mapping.matrix.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/dto/PathCheck.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/RenderRequestService.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/MappingTransformerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/RequestMapperTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunnerTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.2.yaml
Replaced the validation type to string for eline quote place type
https://github.com/mycloudnexus/kraken/issues/369
- [] Bug fix (non-breaking change which fixes an issue)
=> fix(sdk): replaced the validation type to string for eline quote place type

kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/SelectAPI/index.tsx
- use /products/mef.sonata/components/{id} to fetch facet details
- https://github.com/mycloudnexus/kraken/issues/336
- improve loading time of API Mapping page
=> fix(portal): performance improvement mapper setting

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunnerTest.java
made some improvements on integer validation, e.g. [1.0, 100.0] -> [1, 100]
https://github.com/mycloudnexus/kraken/issues/379
Unit test in localhost
=> fix(sdk): made some improvements on integer validation

kraken-app/kraken-app-hub/src/main/resources/application.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/FilterHeaderService.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/service/FilterHeaderServiceTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/application.yml
remove authorization and x-sonata-buyer-key from both main request and branches request in api activity log details
https://github.com/mycloudnexus/kraken/issues/378 [api activity log] remove token from log details
The sensitive data in HTTP headers should be filtered out when persist headers to database
Start kranken applications
Setup API mapping correctly
Send request to API with authorization and x-sonata-buyer-key header
Check the api activity log to make sure authorization and x-sonata-buyer-key headers are not included in response
=> fix(sdk): issue-378 [api activity log] remove token from log details

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/ComponentMgmtController.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/SaveWorkflowTemplateDTO.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/SaveWorkflowTemplateRequest.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ApiComponentService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/ComponentMgmtControllerTest.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/resources/deployment-config/api-targets-mappers/api-target-mapper.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-controller/src/test/resources/deployment-config/api-workflow/api-workflow.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-controller/src/test/resources/deployment-config/product.yaml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/ActionTypeEnum.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/AssetKindEnum.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/TaskEnum.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/WorkflowStageEnum.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/AbstractTask.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/HttpTask.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/facet/ComponentAPITargetFacets.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/facet/ComponentWorkflowFacets.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/AssetsConstants.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/StringUtilsTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-workflow/api-workflow.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-workflow/pom.xml, kraken-java-sdk/pom.xml
Save workflow template endpoint in control plane
Add workflow asset kind in kraken;
Be able to save workflow template in control plane;
=> feat(sdk): [Control Plane] Be able to save workflow template in control plane

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/ResponseCodeTransform.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/ResponseCodeTransformTest.java
change downstream response code to 422 if it equals 400
https://github.com/mycloudnexus/kraken/issues/388
Unit test in local host
=> fix(sdk): change downstream response code to 422 if it equals 400

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/v2/ComponentAPIServerController.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ComponentAPIServerService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/APIServerCreator.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/v2/ComponentAPIServerControllerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/AbstractActionRunner.java
filtered the sync meta data for api server list and set syncMetadata to 'null'.
https://github.com/mycloudnexus/kraken/issues/377
Added Unit test case
=> fix(sdk): filtered the sync meta data for api server list

kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/ApiActivityLogCreator.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/dto/ApiActivityLog.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/entity/ApiActivityLogEntity.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/mapper/ApiActivityLogMapper.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogServiceTest.java, kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/PushLogService.java, kraken-java-sdk/kraken-java-sdk-sync/src/test/java/com/consoleconnect/kraken/operator/sync/service/PushLogServiceTest.java
triggered at should be pushed together with other type of data of each api activity log record
https://github.com/mycloudnexus/kraken/issues/343 push log improvements
=> feat(sdk): issues-343 push log improvements

kraken-app/kraken-app-hub/src/test/resources/mock/apis/api.order.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/apis/api.quote.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.order.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.product.offering.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.quote.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.4.yaml
Used optional chaining to safely access nested properties of quoteItem, product, and productConfiguration.
https://github.com/mycloudnexus/kraken/issues/387
=> fix(sdk): fix internal error in component routing

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/LoadTargetAPIConfigActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/MappingTransformerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/mockData/quoteResponseWithNegativeDutyFreeAmountValue.json, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml
For all 'create quote' use cases: 
If quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.value is either not returned by the seller API or has a negative value, remove quoteItem[0].quoteItemPrice from the response body.
https://github.com/mycloudnexus/kraken/issues/412
Unit test in localhost
=> fix(sdk): add empty or negative value for duty free amount value in quote

kraken-app/kraken-app-portal/package-lock.json
compile node package using a different node version.
https://github.com/mycloudnexus/kraken/issues/323
=> fix(sdk): fix node compile error

kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/model/SyncProperty.java
communicate with mgmt-plane via new endpoints /tenant/agent/callback/**, new client crendential authentication mode will be applied instead of long term token
https://github.com/mycloudnexus/kraken/issues/385
client crendential authentication will be applied to enhance security
=> feat(sdk): issue-385 communicate with mgmt-plane via new endpoints

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.6.yaml
- add mapping template record  v1.7.6
- #413
=> fix(sdk): add mapping template record issue-413 

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/MappingTransformerTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.9.yaml
Resolved the negative double case issue and removed the 'keyName' mapping item for quote uni.
https://github.com/mycloudnexus/kraken/issues/406
https://github.com/mycloudnexus/kraken/issues/412
=> fix(sdk): resolved negative double case and removed keyname mapping item

kraken-app/kraken-app-hub/src/test/resources/expected/expected-10-quote.uni.read.sync.json, kraken-app/kraken-app-hub/src/test/resources/expected/expected-7-quote.eline.read.json, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.eline.read.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.eline.read.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.uni.read.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.uni.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.eline.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.uni.read.sync.yaml
Resolved quote level value for reading quote record
https://github.com/mycloudnexus/kraken/issues/432
Integration test in localhost and verified the output.
=> fix(sdk): fixed quote level value for reading

kraken-app/kraken-app-hub/src/test/resources/expected/expected-10-quote.uni.read.sync.json, kraken-app/kraken-app-hub/src/test/resources/expected/expected-11-quote.eline.add.sync.json, kraken-app/kraken-app-hub/src/test/resources/expected/expected-9-quote.uni.add.sync.json, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.eline.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.eline.read.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.uni.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.uni.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/DateTime.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/toolkit/DateTimeTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/LoadTargetAPIConfigActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/SpELEngineTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.eline.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.uni.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.12.yaml
https://github.com/mycloudnexus/kraken/issues/450
=> fix(sdk): adjust quote templates

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/ResponseCodeTransform.java
Adjust the message content to match the reason field
https://github.com/mycloudnexus/kraken/issues/453
=> fix(sdk): adjust message content same as the reason field

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.14.yaml
fix adding supported type issue in template
https://github.com/mycloudnexus/kraken/issues/441
=> fix(sdk): fix adding supported type issue in template

.github/workflows/ci.yaml, kraken-app/kraken-app-controller/src/main/resources/assets/environments/prod.yaml, kraken-app/kraken-app-controller/src/main/resources/assets/environments/stage.yaml, kraken-app/kraken-app-controller/src/main/resources/assets/product.yaml, kraken-app/kraken-app-controller/src/main/resources/assets/template-upgrade/release.1.0.1.yaml, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/SellerContactService.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/mapper/FacetsMapper.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/AssetKeyGenerator.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/AssetKeyGeneratorTest.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java, kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/mapper_1.json, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/SellerContactInjector.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/service/SellerContactInjectorTest.java
Resolved seller contact key in two planes
https://github.com/mycloudnexus/kraken/issues/467
Unit test only.
=> fix(sdk): resolved seller contact key in two planes

kraken-app/kraken-app-controller/src/main/java/com/consoleconnect/kraken/operator/service/SellerContactsInitializer.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java, kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/mapper_2.json, kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/BuyerSyncHandler.java, kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/GeneralSyncService.java, kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/SellerContactSyncHandler.java, kraken-java-sdk/kraken-java-sdk-sync/src/test/java/com/consoleconnect/kraken/operator/sync/service/GeneralSyncServiceTest.java, kraken-java-sdk/kraken-java-sdk-sync/src/test/resources/data/seller-contact-01.json
Resolved the seller contact can not overwrite the values in data plane.
https://github.com/mycloudnexus/kraken/issues/467
=> fix(sdk): fixed seller contact sync failed

kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/SellerContactSyncHandler.java
Restored the enforced value to match the default configurations for the seller contact sync.
https://github.com/mycloudnexus/kraken/issues/467
=> fix(sdk): recovered enforce value to configuration for seller contacts

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/mapper/FacetsMapper.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.15.yaml
Resolved the loss of source values during control plane upgrades.
https://github.com/mycloudnexus/kraken/issues/462
Unit test verified in localhost
=> fix(sdk): resolved the loss of source values

kraken-app/kraken-app-hub/src/main/resources/application.yaml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/AppProperty.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/model/HttpResponseContext.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/AbstractBodyTransformerFunc.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/PathOperator.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/ResponseCodeTransform.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/ResponseCodeTransformTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/mockData/downstream.error.json
https://github.com/mycloudnexus/kraken/issues/483
=> fix(sdk): remove status from downstream

kraken-app/kraken-app-hub/src/main/resources/application.yaml, kraken-app/kraken-app-portal/.env, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/AppProperty.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/model/HttpResponseContext.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/AbstractBodyTransformerFunc.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/PathOperator.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/ResponseCodeTransform.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/ResponseCodeTransformTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/mockData/downstream.error.json
back port to downstream fix issue-483 
https://github.com/mycloudnexus/kraken/issues/421
=> fix(sdk): back port to downstream fix issue-483 

kraken-java-sdk/kraken-java-sdk-core/pom.xml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/exception/KrakenExceptionHandler.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/AssetsConstants.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/Constants.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/ConstructExpressionUtil.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/StringUtils.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/StringUtilsTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/ResponseCodeTransformTest.java
Resolved the format of downstream message escape issue.
https://github.com/mycloudnexus/kraken/issues/483
Unit test only in localhost
=> fix(sdk): resolve downstream message escape

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/mapper/FacetsMapper.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/toolkit/MapperCopyTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.17.yaml
Added copy of mappers
https://github.com/mycloudnexus/kraken/issues/488
Unit test only
=> fix(sdk): added copy of mappers

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java
Resolved the possible NPE issue
https://github.com/mycloudnexus/kraken/issues/494
=> fix(sdk): fix possible npe

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.read.delete.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.read.delete.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-core/pom.xml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/dto/StateValueMappingDto.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/exception/KrakenExceptionHandler.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/KVPair.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/PathRule.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/facet/ComponentAPITargetFacets.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/AssetsConstants.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/Constants.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/ConstructExpressionUtil.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/StringUtils.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/StringUtilsTest.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java, kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/target-mapper.quote.uni.add.sync-1.yaml, kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/target-mapper.quote.uni.add.sync-2.yaml, kraken-java-sdk/kraken-java-sdk-core/src/test/resources/deployment-config/components/api-targets-mappers/api-target-mapper.quote.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/AbstractBodyTransformerFunc.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/PathOperator.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/RenderRequestService.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/MappingTransformerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/ResponseCodeTransformTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/mockData/quote.eline.can.provide.response.json, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/mockData/quote.eline.response.json, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml
fix more regression issues
https://github.com/mycloudnexus/kraken/issues/421
=> fix(sdk): back port to 1.2.0 -- fix more regression issues

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.read.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/RenderRequestService.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.19.yaml
Added quote state validation for reading the existed quote records
https://github.com/mycloudnexus/kraken/issues/488
https://github.com/mycloudnexus/kraken/issues/494
=> fix(sdk): added quote read sync state validation

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.read.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/MappingTransformerTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.20.yaml
Re-added 'quoteLevel' into the response body as requested by QA.
https://github.com/mycloudnexus/kraken/issues/488
=> fix(sdk): added quote level back as request from qa

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.read.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingTransformer.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/RenderRequestService.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/MappingTransformerTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.read.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.read.sync.yaml
fix quoteLevel issue
https://github.com/mycloudnexus/kraken/issues/421
=> fix(sdk): back port 1.2.0--fix quoteLevel issue

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientHeartbeatEventHandler.java
When data plane upgrade from one version to another new version , client record in control plane wont update the related app version  .
- #506
=> fix(sdk): issue-506 - update new app version after upgrade

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientHeartbeatEventHandler.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/AppConfig.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/jpa/KrakenCustomHibernatePropertiesCustomizer.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/jpa/KrakenCustomNamingStrategy.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/jpa/KrakenCustomSpringImplicitNamingStrategy.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/AppProperty.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/KrakenCustomHibernatePropertiesCustomizerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/repo/HttpRequestRepository.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DBCrudActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/DBCrudActionRunnerTest.java
… instance id
back port issue-508 Handling more than one records sharing the same produt instance id
https://github.com/mycloudnexus/kraken/issues/421
=> fix(sdk): back port issue-508 Handling more than one records sharing the same produt instance id

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-specs/api-spec.address.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-specs/api-spec.inventory.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-specs/api-spec.order.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-specs/api-spec.product.offering.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-specs/api-spec.quote.yaml
Upgraded versions of spec files
https://github.com/mycloudnexus/kraken/issues/418
=> feat(sdk): upgraded version of spec files

kraken-app/kraken-app-controller/src/main/resources/application.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.poq.eline.add.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.poq.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ApiComponentService.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ComponentTagService.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/TargetMappingChecker.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/upgrade/AbstractUpgradeSourceService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/toolkit/TargetMappingCheckerTest.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/model/AppProperty.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.poq.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.poq.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.22.yaml
1.Added labels for product offering qualification;
2. Setting 'allowValueLimit' to false for bandwidth of POQ;
3.Moved the sequence of POQ to the second position after Address Validation Component;
4.Setting POQ reading with no need to mapping;
https://github.com/mycloudnexus/kraken/issues/491
Unit test only
=> fix(sdk): added labels for product offering qualification

kraken-app/kraken-app-portal/package-lock.json, kraken-app/kraken-app-portal/package.json, kraken-java-sdk/kraken-java-sdk-workflow/src/main/java/com/consoleconnect/kraken/operator/workflow/service/WorkflowDeployService.java, kraken-java-sdk/kraken-java-sdk-workflow/src/test/java/com/consoleconnect/kraken/operator/workflow/service/WorkflowEventListenerTest.java
Fix fail to deploy workflow to conductor when the workflow definition is new(initial deployment of the workflow definition.
https://github.com/mycloudnexus/kraken/issues/523
=> fix(sdk): fix workflow initial deploy failure

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ApiComponentService.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/AssetsConstants.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-workflow/api-workflow.order.uni.delete.yaml
be able to update workflow enabled flag
https://github.com/mycloudnexus/kraken/issues/319
=> fix(sdk): be able to update workflow enabled flag

kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.poq.eline.add.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.poq.eline.read.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.poq.uni.add.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.poq.uni.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.poq.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.poq.eline.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.poq.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.poq.uni.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.23.yaml
Added complete date for poq.
https://github.com/mycloudnexus/kraken/issues/535
https://github.com/mycloudnexus/kraken/issues/536
=> fix(sdk): added complete date for poq

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.uni.add.yaml
Removed the duration mapping items in response and added them into the basic templates.
https://github.com/mycloudnexus/kraken/issues/541
=> feat(sdk): update order creating templates

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/filter/WorkflowActionFilterFactory.java
clean some attributes in headers
https://github.com/mycloudnexus/kraken/issues/334
=> fix(sdk): clean some attributes in headers

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/filter/WorkflowActionFilterFactory.java
remove header key ignore case
https://github.com/mycloudnexus/kraken/issues/334
=> fix(sdk): remove header key ignore case

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/filter/WorkflowActionFilterFactory.java
fix header issue in workflow
https://github.com/mycloudnexus/kraken/issues/565
=> fix(sdk): issu- 565 fix header issue in workflow

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java, kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/mapper_merged.json, kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/mapper_old.json
- Set requiredMapping to false when change system mapping to customized mapping.
https://github.com/mycloudnexus/kraken/issues/530
=> fix(sdk): issues-530 mapping template upgrade improvement - fix requiredMapping

kraken-app/kraken-app-portal/src/__test__/pages/Homepage/components/ActivityDiagrams.test.tsx, kraken-app/kraken-app-portal/src/pages/HomePage/components/ActivityDiagrams/index.tsx
Fix to update env ID being sent to API to fetch data
https://github.com/mycloudnexus/kraken/issues/479
Bug fix for wrong env ID being sent during load
=> fix(portal): send productionId for production data

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/ApiMapperDeploymentDTO.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientDeploymentEventHandler.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/model/DeploymentFacet.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/model/EnvironmentClient.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ProductDeploymentService.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/tools/DeploymentErrorHelper.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/v2/ClientPubSubControllerTest.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/v2/ProductDeploymentControllerTest.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/v2/TemplateUpgradeControllerTest.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/toolkit/DeploymentHelperTest.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/client/ClientInstanceDeployment.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/dto/DeployComponentError.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/entity/EnvironmentClientEntity.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/ErrorSeverityEnum.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/event/ReportConfigReloadEvent.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/exception/KrakenDeploymentException.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/DeploymentErrorHelper.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/toolkit/DeploymentErrorHelperTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/service/workflow/WorkflowTaskConfigTest.java, kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/PullDeploymentService.java, kraken-java-sdk/kraken-java-sdk-sync/src/test/java/com/consoleconnect/kraken/operator/sync/service/PullDeploymentServiceTest.java, kraken-java-sdk/kraken-java-sdk-workflow/src/main/java/com/consoleconnect/kraken/operator/workflow/service/WorkflowDeployService.java
Deployment status is stuck on In_progress status and block any further operations.
Should change status to FAILED if deployment fails
https://github.com/mycloudnexus/kraken/issues/570
=> feat(sdk): issues-570 [BUG] upgrade from Control plane to Stage Data Plane hang

kraken-app/kraken-app-hub/src/main/resources/application.yaml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/exception/KrakenException.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/BuyerCheckerService.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.quote.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.26.yaml
Made some improvements on the error message of invalid token
https://github.com/mycloudnexus/kraken/issues/557
=> fix(sdk): make improvement on invalid buyer error message

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ProductDeploymentService.java
fix missing workflow deployment in deployment history list
https://github.com/mycloudnexus/kraken/issues/570
=> feat(sdk): issues-570 fix missing workflow deployment in deployment list

kraken-java-sdk/kraken-java-sdk-sync/src/main/java/com/consoleconnect/kraken/operator/sync/service/BuyerSyncHandler.java
When buyer info changed, should synchronize from control plane  to data plane 
- #598
=> fix(sdk): fix buyer sync

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.inventory.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.32.yaml
add mock response action in inventory list
https://github.com/mycloudnexus/kraken/issues/603
=> fix(sdk): add mock response action in inventory list

kraken-app/kraken-app-controller/src/main/resources/application.yaml
update order of mapper for modify cases
https://github.com/mycloudnexus/kraken/issues/551
=> fix(sdk): update order of mapper for modify cases

kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/EnvironmentActivityTable/index.tsx
Update column filters for status codes and methods to allow multiple values
https://github.com/mycloudnexus/kraken/issues/560
Allow multiple filters in FE to accommodate BE changes
=> feat(portal): filter log by multiple status codes and multiple methods

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/TemplateUpgradeService.java
[BUG] Template upgrading should be marked as completed in case of no running mapping
https://github.com/mycloudnexus/kraken/issues/621
=> fix(sdk): issues-621 [BUG] Template upgrading should be marked as completed in case of no running mapping

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.quote.eline.modify.sync.yaml
Fixed the wrong static value configuration of 'action' for quote eline modify
https://github.com/mycloudnexus/kraken/issues/624
=> fix(sdk): fix quote eline modify action configurations

kraken-app/kraken-app-portal/src/__test__/services/products.test.ts, kraken-app/kraken-app-portal/src/hooks/product/index.ts, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/ActivityDetailModal/ActivityDetailItem/__test__/index.test.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/EnvironmentActivityTable/index.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/PushHistoryDrawer/index.tsx, kraken-app/kraken-app-portal/src/services/products.ts, kraken-app/kraken-app-portal/src/utils/helpers/name.ts, kraken-app/kraken-app-portal/src/utils/types/env.type.ts
Add product Type column to activity log table
https://github.com/mycloudnexus/kraken/issues/559
=> feat(portal): add product Type column to activity log table

kraken-app/kraken-app-portal/src/components/ExampleValueModal/index.tsx, kraken-app/kraken-app-portal/src/pages/APIServerList/index.tsx, kraken-app/kraken-app-portal/src/pages/Buyer/components/NewBuyerModal/index.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/PushHistoryDrawer/index.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentOverview/components/ModalNewDeployment/index.tsx, kraken-app/kraken-app-portal/src/pages/UserManagement/components/ResetPwdModal/index.tsx, kraken-app/kraken-app-portal/src/pages/UserManagement/components/UserModal/index.tsx
Make modals and drawers with editable fields not mask closeable
https://github.com/mycloudnexus/kraken/issues/533
=> fix(portal): make modals and drawers with editable fields not mask closeable

kraken-app/kraken-app-portal/src/__test__/pages/NewAPIMapping/component.test.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/RequestItem/index.tsx
Convert source values to string before passing to BE
https://github.com/mycloudnexus/kraken/issues/610
Solves the issue where integer source values are sent to BE
=> fix(portal): source value converted to string

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ApiComponentService.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ComponentTagService.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/TemplateUpgradeService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/v2/TemplateUpgradeControllerTest.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/toolkit/TestConstant.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/resources/deployment-config/apis/api.order.yaml, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/dto/ApiUseCaseDto.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/ApiUseCaseDtoTest.java
if api is set with 1:1, when doing upgrade, should only upgrade 1:1 template and mapping file.
if api is set with 1:m, when doing upgrade, should upgrade both 1:1 and 1:m templates and mapping files.
https://github.com/mycloudnexus/kraken/issues/627
=> fix(sdk): issues-627 [BUG] [BE] upgrade: separate 1:1 upgrade and 1:m upgrade

kraken-app/kraken-app-portal/src/__test__/pages/Buyer/index.test.tsx, kraken-app/kraken-app-portal/src/pages/Buyer/index.tsx
Popup modal of new token when reactivating a buyer
https://github.com/mycloudnexus/kraken/issues/612
=> feat(portal): reactivating buyer shows new token in modal

kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/SelectAPI/index.tsx
Fix for unable to set seller api path issue
https://github.com/mycloudnexus/kraken/issues/620
Fix for unable to set seller api path issue
=> fix(portal): unable to set seller api path fix

kraken-app/kraken-app-portal/src/hooks/product/index.ts
Prevent api call when target mapper is undefined
https://github.com/mycloudnexus/kraken/issues/623
Fixes the issue where there is an extra api call made when refreshing mapping details page
=> fix(portal): wrong api call during refresh of mapping details page

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.inventory.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.order.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.39.yaml
fix forward downstream issue
https://github.com/mycloudnexus/kraken/issues/640
=> fix(sdk): fix forward downstream issue

kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunnerTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.order.common.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.eline.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.order.eline.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.order.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.quote.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.quote.eline.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.quote.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.quote.eline.modify.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.quote.uni.add.sync.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.quote.uni.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.41.yaml
improvement error message for unsupported use case
https://github.com/mycloudnexus/kraken/issues/643
https://github.com/mycloudnexus/kraken/issues/644
=> fix(sdk): improvement error message for unsupported use case

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java
Ingestion templates to database will fail when start kraken control plane with new database.
https://github.com/mycloudnexus/kraken/issues/596
=> fix(sdk): issue-596 fix load template failure

kraken-app/kraken-app-controller/src/main/resources/application.yaml, kraken-app/kraken-app-portal/src/__test__/pages/StandardAPIMappingTable/index.test.tsx, kraken-app/kraken-app-portal/src/pages/StandardAPIMappingTable/index.tsx, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/v2/ComponentController.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/controller/ComponentController.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/dto/SearchQueryParams.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/JsonToolkit.java
Fixed the breadcrumbs in the component mapping page
https://github.com/mycloudnexus/kraken/issues/652
=> fix(sdk): component breadcrumbs

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/exception/KrakenException.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunnerTest.java
fix error message when use case is not supported
https://github.com/mycloudnexus/kraken/issues/663
=> fix(sdk): fix error message when use case is not supported

kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/EnvironmentActivityTable/index.tsx, kraken-app/kraken-app-portal/src/utils/helpers/name.ts
fix product type filter in activity log page
https://github.com/mycloudnexus/kraken/issues/559
=> fix(portal): issue-559 fix product type filter in activity log page

kraken-app/kraken-app-controller/src/main/resources/application.yaml, kraken-app/kraken-app-portal/src/__test__/pages/StandardAPIMappingTable/index.test.tsx, kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.tsx, kraken-app/kraken-app-portal/src/pages/StandardAPIMappingTable/index.tsx
Resolved the breadcrumbs and component list in the mapping pages linked from component pages.
https://github.com/mycloudnexus/kraken/issues/652
=> fix(sdk): resolved the mapping breadcrumbs

kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/PushHistoryDrawer/index.tsx
clear default selected push date in activity log push page
https://github.com/mycloudnexus/kraken/issues/427
=> fix(portal): issue-427 clear default selected push date

kraken-app/kraken-app-agent/src/main/resources/application.yaml
Remove the default cron-job configurations for agents, as theose configurations should vary according to agent types
https://github.com/mycloudnexus/kraken/issues/596
=> feat(sdk): issue-596 remove the default cron-job configurations for agents

kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.tsx
Bugfix ported from release/2.0: [BUG] [FE] Deploy history is not up-to-date
https://github.com/mycloudnexus/kraken/issues/680
=> fix(portal): issue-680 [BUG] [FE] Deploy history is not up-to-date

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.order.common.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.order.common.modify.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.modify.yaml
Bugfix ported from release/2.0: adjust modify eline order common
https://github.com/mycloudnexus/kraken/issues/679
=> fix(sdk): issue-679 adjust modify eline order common

kraken-app/kraken-app-controller/src/main/resources/db/migration/V6__update_asset_description_idx_max_length.sql, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/entity/UnifiedAssetEntity.java
Merge bugfix from release/2.0:  issues-686 fail to upgrade template caused by description value too long error
https://github.com/mycloudnexus/kraken/issues/686
=> fix(sdk): issues-686 fail to upgrade template caused by description value too long error

kraken-app/kraken-app-controller/src/main/resources/application.yaml, kraken-app/kraken-app-hub/src/test/resources/mock/apis/api.address.yaml, kraken-app/kraken-app-portal/src/__test__/pages/EnvironmentActivityLog/PushHistoryDrawer/index.test.tsx, kraken-app/kraken-app-portal/src/__test__/pages/EnvironmentActivityLog/index.test.tsx, kraken-app/kraken-app-portal/src/pages/AuditLog/index.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/EnvironmentActivityTable/index.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/PushHistoryDrawer/index.tsx, kraken-app/kraken-app-portal/src/utils/helpers/name.ts, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/enhancer/ProductTypeRecorder.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/JavaScriptEngineActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/PatternActionRunner.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/ResponseCodeTransform.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/JavaScriptEngineActionRunnerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/PatternActionRunnerTest.java, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.address.yaml
Merge bugfix from release/2.0: fix display name of product type
https://github.com/mycloudnexus/kraken/issues/559
=> fix(misc): issues-559 fix display name of product type

kraken-app/kraken-app-portal/package-lock.json, kraken-app/kraken-app-portal/src/__test__/pages/EnvironmentOverview/index.test.tsx, kraken-app/kraken-app-portal/src/hooks/product/index.ts, kraken-app/kraken-app-portal/src/pages/EnvironmentOverview/index.tsx, kraken-app/kraken-app-portal/src/services/products.ts, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/EnvAccessTokenController.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/repo/APITokenRepository.java, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/APITokenService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/EnvAccessTokenControllerTest.java
Verify the validity of the API token and check if it has been deprecated.
- #697
=> fix(sdk): issue-697 Verify the validity of the API token and check if it has been deprecated.

kraken-app/kraken-app-portal/src/__test__/services/products.test.ts, kraken-app/kraken-app-portal/src/utils/helpers/request.ts
refactor basic authentication type
https://github.com/mycloudnexus/kraken/issues/681
=> fix(misc): issue-681 refactor basic authentication type

kraken-app/kraken-app-portal/src/components/AuthProviders/basic/components/header/index.tsx, kraken-app/kraken-app-portal/src/router/index.tsx, kraken-app/kraken-app-portal/src/utils/constants/route.ts
change login url back to /login
https://github.com/mycloudnexus/kraken/issues/681
=> feat(misc): issue-681 change login url back to /login

kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/ComponentAPIServerService.java
fix missing basePath in api server list
https://github.com/mycloudnexus/kraken/issues/710
=> fix(sdk): fix missing basePath in api server list

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.order.common.read.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.order.common.read.delete.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.2.0.4.yaml
remove expectedCompletionDate from response mapping template
https://github.com/mycloudnexus/kraken/issues/739
=> fix(sdk): remove expectedCompletionDate from response mapping

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.order.common.add.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.2.0.5.yaml
add itemTerm.duration.units and itemTerm.duration.amount in add order
https://github.com/mycloudnexus/kraken/issues/738
=> fix(sdk): add itemTerm.duration.units and itemTerm.duration.amount in add order

kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.inventory.common.list.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-common-mappers/api-target-mapper.inventory.common.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.2.0.6.yaml
add lastUpdateDate and createdDate to inventory response
https://github.com/mycloudnexus/kraken/issues/740
=> fix(sdk): add lastUpdateDate and createdDate to inventory response

kraken-app/kraken-app-portal/src/pages/EnvironmentOverview/components/EnvStatus/index.tsx
remove unused icon in env selection
https://github.com/mycloudnexus/kraken/issues/698
=> fix(portal): kraken-698 remove unused icon in env selection

kraken-app/kraken-app-portal/src/pages/APIServerList/index.tsx, kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/commonHook.tsx
- json format issue in address validation;
- change 'add' to 'edit' in contact information page;
https://github.com/mycloudnexus/kraken/issues/719
https://github.com/mycloudnexus/kraken/issues/717
=> fix(portal): improvements on json format, edit contact information page

kraken-app/kraken-app-hub/src/test/java/com/consoleconnect/kraken/operator/TestConfiguration.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/JsonToolkit.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/func/SpelFunc.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/KrakenAPIRouteLocatorImpl.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/template/SpELEngine.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/GatewayTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/SpELEngineTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/TestConfiguration.java, kraken-java-sdk/kraken-java-sdk-gateway/src/test/resources/mockData/facetData.json, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.inventory.eline.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.inventory.uni.read.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/apis/api.inventory.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml, kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.2.0.7.yaml
enable inventory by id to insert fields into productConfiguration
https://github.com/mycloudnexus/kraken/issues/725
=> fix(sdk): enable inventory by id to insert fields into productConfiguration

kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/JsonToolkit.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/filter/ApiLogInputGlobalFilter.java
ignore invalid json request format
https://github.com/mycloudnexus/kraken/issues/770
=> fix(sdk): ignore invalid json request format

kraken-app/kraken-app-portal/src/__test__/pages/EnvironmentActivityLog/PushHistoryList/index.test.tsx, kraken-app/kraken-app-portal/src/__test__/pages/EnvironmentActivityLog/index.test.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/EnvironmentActivityTable/index.tsx, kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/index.tsx, kraken-app/kraken-app-portal/src/stores/buyer.store.tsx, kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/BuyerService.java, kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/BuyerControllerTest.java, kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java, kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java
add buyer filter in both frontend and backend
https://github.com/mycloudnexus/kraken/issues/561
=> feat(sdk): add buyer filter in activity log page

kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.tsx
fix revert issue in mapping detail page
https://github.com/mycloudnexus/kraken/issues/714
=> fix(portal): fix revert issue in mapping detail page

kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/BuyerControllerTest.java, kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/RenderRequestService.java
fix hybrid convert issue
https://github.com/mycloudnexus/kraken/issues/801
=> fix(sdk): fix hybrid convert issue
