- .github/workflows/ci.yaml
- kraken-java-sdk/kraken-java-sdk-core/pom.xml
- kraken-java-sdk/kraken-java-sdk-test/pom.xml
- kraken-java-sdk/pom.xml
The CI reported a couple of cirtical/high vulnerabilities, looks like the root cause is the CI tool can't detect the maven packages used by the project (  vulnerable version is empty), config the version in the pom.xml for the dependencies should be able to fix this issue.
<br class="Apple-interchange-newline">
> fix(sdk): fix critical/high vulenerabilities

- kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/v2/ProductDeploymentControllerTest.java
Everything is good when running https://github.com/mycloudnexus/kraken/blob/main/kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/v2/ProductDeploymentControllerTest.java
But there are some test cases failed when running test on the full project. 
The issue should be caused by multiple test cases may generate the same cases, which cause the assertion not correct.
> fix(sdk): fix the wrong test case assertion

- .github/workflows/release.yml
There is a error on building the docker image in release pipeline:
```
There is a error when building the docker image:
Run docker/build-push-action@v5
GitHub Actions runtime token ACs
Docker info
Proxy configuration
Buildx version
Builder info
/usr/bin/docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --file ./docker/app-controller/Dockerfile --iidfile /home/runner/work/_temp/docker-actions-toolkit-njN0kl/build-iidfile-7aa0803546.txt --tag cloudnexusopsdockerhub/kraken-app-controller:1.0.1 --metadata-file /home/runner/work/_temp/docker-actions-toolkit-njN0kl/build-metadata-8a96b30582.json --push .
ERROR: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at …
```
> fix(misc): setup docker buildx in release pipeline

- .github/workflows/release.yml
After appying the patch https://github.com/mycloudnexus/kraken/pull/11
There is a  error:
```
Error: ERROR: failed to initialize builder builder-dccfcead-6ba3-4fa2-873a-3f59e17e0669 (builder-dccfcead-6ba3-4fa2-873a-3f59e17e06690): error during connect: Get "http://build-context:2375/v1.47/containers/buildx_buildkit_builder-dccfcead-6ba3-4fa2-873a-3f59e17e06690/json": dial tcp: lookup build-context on 127.0.0.53:53: server misbehaving
```
- https://github.com/mycloudnexus/kraken/issues/1
> fix(misc): delete cache from docker build

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/bump-version.yaml
- .github/workflows/lint-pull-request.yaml
Add a bump version github workflow, the workflow should be triggered manually and the following inputs required:
- branch
- new-version
The workflow will:
-  create a new branch based on the branch
- set the new-version in pom.xml and package.json files
- create a PR to the branch
> build(ci-cd): add bump version github workflow

- .github/workflows/ci.yaml
- pom.xml
- sonar-project.properties
1. create two projects in sonarcloud ( mono-repo)
2. integrate with sonar-cloud in the ci to report code coverage
> build(misc): integrate with sonarcloud to support java and nodejs code coverage

- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/StartGuideController.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/start/ApiMappingInfoDto.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/start/DeploymentInfoDto.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/start/SellerApiServerRegistrationInfoDto.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/start/StartGuideInfoDto.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/start/StartGuideService.java
- kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/api/StartGuideControllerTest.java
- kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/service/start/StartGuideServiceTest.java
- kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/repo/UnifiedAssetRepository.java
Add new endpoint _**/start/guide/{productId}?kind={kind}**_ for new home page - quick start guide
Example of the response:
```json
{
"sellerApiServerRegistrationInfo": {
"atLeastOneSellerApiRegistered": true
},
"apiMappingInfo": {
"atLeastOneMappingCompleted": true
},
"deploymentInfo": {
"atLeastOneApiDeployedToStage": false,
"atLeastOneBuyerRegistered": true,
"atLeastOneApiDeployedToProduction": false
}
}
```
https://github.com/mycloudnexus/kraken/issues/29
> feat(sdk): kraken-29 - add new endpoint for quick start guide

- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/api/EnvAPIActivityStatisticsController.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/statistics/ApiRequestActivityStatistics.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/statistics/EndpointUsage.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/statistics/ErrorApiRequestStatistics.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/statistics/ErrorBreakdown.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/statistics/MostPopularEndpointStatistics.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/dto/statistics/RequestStatistics.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/statistics/ApiActivityStatisticsService.java
- kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/api/EnvAPIActivityStatisticsControllerTest.java
- kraken-java-sdk/kraken-java-sdk-controller/src/test/java/com/consoleconnect/kraken/operator/controller/service/statistics/ApiActivityStatisticsServiceTest.java
- kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/repo/ApiActivityLogRepository.java
- kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/request/ApiStatisticsSearchRequest.java
Add 3 new endpoints:
GET /products/{productId}/envs/{envId}/statistics/api-activity-requests?requestStartTime={startTime}&requestEndTime={endTime}
Example of the response:
```json
"code": 200,
"message": "OK",
"data": {
"requestStatistics": [
{
"date": "2024-10-17",
"success": 388,
"error": 620
},
{
"date": "2024-10-18",
"success": 357,
"error": 651
},
{
"date": "2024-10-19",
"success": 393,
"error": 615
}
]
}
}
```
GET /products/{productId}/envs/{envId}/statistics/error-requests?requestStartTime={startTime}&requestEndTime={endTime}
Example of the response:
```json
{
"code": 200,
"message": "OK",
"data": {
"errorBreakdowns": [
{
"date": "2024-10-17",
"errors": {
"400": 237,
"401": 229,
"404": 24,
"500": 130
}
},
{
"date": "2024-10-18",
"errors": {
"400": 228,
"401": 229,
"404": 24,
"500": …
```
> feat(sdk): kraken-19 - add endpoints for api request statistics

- kraken-app/kraken-app-portal/src/components/APIServerDrawer/index.tsx
- kraken-app/kraken-app-portal/src/components/Method/index.module.scss
- kraken-app/kraken-app-portal/src/components/Method/index.tsx
- kraken-app/kraken-app-portal/src/pages/APIServerList/components/APIServerCard.tsx
- kraken-app/kraken-app-portal/src/pages/APIServerList/index.tsx
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionDetail/index.module.scss
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionDetail/index.tsx
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionSelect/index.tsx
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/index.tsx
- kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/HeaderMapping/index.tsx
- kraken-app/kraken-app-portal/src/pages/NewAPIMapping/index.tsx
- kraken-app/kraken-app-portal/src/utils/types/common.type.ts
- Api mapping: fix seller api is not restored to default after clicking Restore button
- fix some minor UI issues
- [[BUG][FE] [upgrade v2] status filter - content should be auto refreshed](https://github.com/mycloudnexus/kraken/issues/135)
- [[improvement] restore button on mapping page does not restore seller endpoint](https://github.com/mycloudnexus/kraken/issues/143)
- [[improvement] seller list page layout update](https://github.com/mycloudnexus/kraken/issues/90)
> fix(portal): restore seller api to default & some minor UI issues

- kraken-java-sdk/kraken-java-sdk-auth/src/main/java/com/consoleconnect/kraken/operator/auth/model/AuthDataProperty.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientServerAPIHandler.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/BuyerService.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/EndPointUsageCalculator.java
- kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/service/TemplateUpgradeService.java
- kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/toolkit/Constants.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/service/BuyerCheckerService.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/service/BuyerCheckServiceTest.java
- https://github.com/mycloudnexus/kraken/issues/126
- https://github.com/mycloudnexus/kraken/issues/35
- https://github.com/mycloudnexus/kraken/issues/163
> fix(sdk): fixed error show api use case in  seller api server module

- kraken-app/kraken-app-portal/src/pages/NewAPIServer/components/SelectAPIServer.tsx
- remove useMemo from form field to avoid cache undefined
#184
> fix(portal): remove useMemo from form field to avoid cache undefined

- kraken-app/kraken-app-portal/src/__test__/pages/MappingTemplate/index.test.tsx
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionDetail/UpgradeProcess.tsx
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/index.tsx
fix mapping template is not showing correct upgrade status
- [[1.0][rc] mapping template process diagram is not showing correct status](https://github.com/mycloudnexus/kraken/issues/192)
> fix(portal): fix mapping template is not showing correct upgrade status

- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.add.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.add.yaml
- kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/MappingTypeEnum.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/LoadTargetAPIConfigActionRunner.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunner.java
https://github.com/mycloudnexus/kraken/issues/209
> feat(sdk): support discrete magnitude checking

- kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionDetail/index.tsx
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionSelect/index.module.scss
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/components/VersionSelect/index.tsx
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/index.module.scss
- kraken-app/kraken-app-portal/src/pages/MappingTemplate/index.tsx
- kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/DeployHistory/index.tsx
- kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.module.scss
- kraken-app/kraken-app-portal/src/pages/StandardAPIMapping/index.tsx
- kraken-app/kraken-app-portal/src/pages/UserManagement/index.tsx
- filtering users by state and role
- fix standard api mapping page layout when loading
- show mapping versions in mapping template page
- [Mapping page loading behavior enhancement](https://github.com/mycloudnexus/kraken/issues/265)
- [[control plane][FE] filter user by role and enabled state](https://github.com/mycloudnexus/kraken/issues/270)
- [[BUG] For selected version, version number together with standard version name should change to highlighted color (primary blue)](https://github.com/mycloudnexus/kraken/issues/267)
- [[BUG] [FE] running mapping template version of 3 planes are not showing up](https://github.com/mycloudnexus/kraken/issues/248)
> fix(portal): filter users by state and role and some minor changes

- kraken-app/kraken-app-portal/src/pages/EnvironmentActivityLog/components/PushHistoryModal/index.tsx
Fixes:
1. Future time range should not be selected in date picker
2. After user selected date range and environment, label "Number of activity logs filtered" is missing
3. When log is filtered as 0. "OK" button should be disabled
#277
> fix(portal): push activity log UI issues

- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.add.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.add.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/mapping-matrix/mapping.matrix.order.eline.add.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/mapping-matrix/mapping.matrix.order.uni.add.yaml
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/dto/PathCheck.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunner.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/MappingMatrixCheckerActionRunnerTest.java
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.add.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.add.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.eline.add.sync.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.quote.uni.add.sync.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.order.eline.add.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.order.uni.add.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.6.3.yaml
Added data type validation rules for creating order of UNI and Eline.
https://github.com/mycloudnexus/kraken/issues/290
> fix(sdk): added data type validation rules for order creating

- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.delete.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.delete.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/apis/api.order.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/mapping-matrix/mapping.matrix.address.validation.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/mapping-matrix/mapping.matrix.order.eline.delete.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/mapping-matrix/mapping.matrix.order.uni.delete.yaml
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DataTypeChecker.java
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.delete.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.delete.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.address.validation.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.order.eline.delete.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/mapping-matrix/mapping.matrix.order.uni.delete.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.6.4.yaml
Added  validation rules of data type for order deleting.
https://github.com/mycloudnexus/kraken/issues/293
https://github.com/mycloudnexus/kraken/issues/276
https://github.com/mycloudnexus/kraken/issues/279
> fix(sdk): added datatype validation for order deleting

- kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/RequestItem/SourceInput.tsx
- kraken-app/kraken-app-portal/src/pages/NewAPIMapping/components/ResponseItem/TargetInput.tsx
show tooltip on sonata predefined mapping api use cases
- [[Improvement] All the properties from predefined mapping template should not be editable and shown as read-only form](https://github.com/mycloudnexus/kraken/issues/299)
> fix(portal): show tooltip on sonata predefined mapping api use cases

- kraken-app/kraken-app-hub/src/test/resources/expected/expected-10-quote.uni.read.sync.json
- kraken-app/kraken-app-hub/src/test/resources/expected/expected-7-quote.eline.read.json
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.eline.delete.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets-mappers/api-target-mapper.order.uni.delete.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.eline.read.sync.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.eline.read.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.uni.read.sync.yaml
- kraken-app/kraken-app-hub/src/test/resources/mock/api-targets/api-target.quote.uni.read.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.eline.delete.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets-mappers/api-target-mapper.order.uni.delete.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.eline.read.sync.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.eline.read.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.uni.read.sync.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/api-targets/api-target.quote.uni.read.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/product.yaml
- kraken-java-sdk/kraken-java-sdk-mef/src/main/resources/mef-sonata/template-upgrade/release.1.7.8.yaml
1. Removed 'productOrderItem[0].product.productOffering.id' in the mapper for deleting order;
2. Added 'qouteLevel' for quote reading;
https://github.com/mycloudnexus/kraken/issues/413
https://github.com/mycloudnexus/kraken/issues/432
> fix(sdk): removed product offering id for deleteing order

- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/repo/HttpRequestRepository.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/main/java/com/consoleconnect/kraken/operator/gateway/runner/DBCrudActionRunner.java
- kraken-java-sdk/kraken-java-sdk-gateway/src/test/java/com/consoleconnect/kraken/operator/gateway/runner/DBCrudActionRunnerTest.java
An exception occurred while routing the inventory read because the 'add' and 'delete' operations share the same product instance ID.
This PR has resolve the above issue.
https://github.com/mycloudnexus/kraken/issues/508
Unit test only
> fix(sdk): resolved exception while two records share the same instance id

- kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetService.java
- kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/UnifiedAssetServiceTest.java
- kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/workflow_merged.yaml
- kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/workflow_new.yaml
- kraken-java-sdk/kraken-java-sdk-core/src/test/resources/data/workflow_old.yaml
Current only api mapper template support merge operation when upgrade template. All other template kinds including workflow use overwrite mode, which means the data configured by customer in running version will be lost after upgrading.
Merge operation on workflow should be supported. Most of the workflow merge operations are same as api mapper, exception for the following aspects:
Cusomer fields:
- HttpTask.endpoint rule: follow 1:1 mapping
- HttpTask.conditionCheck rule: merge user data to new template
System fields:
- HttpTask.taskName
- HttpTask.taskType
- HttpTask.description
- HttpTask.buildInTask
- HttpTask.notificationUrl
rule: use new template
https://github.com/mycloudnexus/kraken/issues/593
> feat(sdk): issues-593 support workflow template merge when upgrade template
